;//Alias header file for CHM project
;//Automatically generated by Easy CHM.
;//Website : http://www.zipghost.com
;//Email   : webmaster@zipghost.com
;//Date    : 2017/3/9 星期四 16:34:27

;//NOTE:
;//All strings after the ";" are commnets, they will be ignored by the CHM Compiler.

IDH_1069=index.htm	; Redirect
IDH_1068=Docs\_Body.htm	; Graphics32 Help
IDH_1000=Docs\Overview\Changes.htm	; Changes
IDH_1002=Docs\Overview\Deprecated.htm	; Deprecated
IDH_1003=Docs\Overview\Example.htm	; Example
IDH_1004=Docs\Overview\FAQ.htm	; FAQ
IDH_1005=Docs\Overview\License.htm	; License
IDH_1007=Docs\Overview\_Body.htm	; Overview
IDH_1006=Docs\Overview\Rounding.htm	; Rounding
IDH_1001=Docs\Overview\Changes_ZH.html	; 变化
IDH_1067=Docs\Units\ClipperLib\_Body.htm	; ClipperLib
IDH_1014=Docs\Units\ClipperLib\Classes\Clipper\_Body.htm	; Clipper
IDH_1008=Docs\Units\ClipperLib\Classes\Clipper\Methods\Constructor.htm	; Constructor
IDH_1009=Docs\Units\ClipperLib\Classes\Clipper\Methods\Execute.htm	; Execute
IDH_1010=Docs\Units\ClipperLib\Classes\Clipper\Properties\PreserveCollinear.htm	; PreserveCollinear
IDH_1011=Docs\Units\ClipperLib\Classes\Clipper\Properties\ReverseSolution.htm	; ReverseSolution
IDH_1012=Docs\Units\ClipperLib\Classes\Clipper\Properties\StrictlySimple.htm	; StrictlySimple
IDH_1013=Docs\Units\ClipperLib\Classes\Clipper\Properties\ZFillFunction.htm	; ZFillFunction
IDH_1019=Docs\Units\ClipperLib\Classes\ClipperBase\_Body.htm	; ClipperBase
IDH_1015=Docs\Units\ClipperLib\Classes\ClipperBase\Methods\AddPath.htm	; AddPath
IDH_1016=Docs\Units\ClipperLib\Classes\ClipperBase\Methods\AddPaths.htm	; AddPaths
IDH_1017=Docs\Units\ClipperLib\Classes\ClipperBase\Methods\Clear.htm	; Clear
IDH_1018=Docs\Units\ClipperLib\Classes\ClipperBase\Methods\GetBounds.htm	; GetBounds
IDH_1027=Docs\Units\ClipperLib\Classes\ClipperOffset\_Body.htm	; ClipperOffset
IDH_1020=Docs\Units\ClipperLib\Classes\ClipperOffset\Methods\AddPath.htm	; AddPath
IDH_1021=Docs\Units\ClipperLib\Classes\ClipperOffset\Methods\AddPaths.htm	; AddPaths
IDH_1022=Docs\Units\ClipperLib\Classes\ClipperOffset\Methods\Clear.htm	; Clear
IDH_1023=Docs\Units\ClipperLib\Classes\ClipperOffset\Methods\Constructor.htm	; Constructor
IDH_1024=Docs\Units\ClipperLib\Classes\ClipperOffset\Methods\Execute.htm	; Execute
IDH_1025=Docs\Units\ClipperLib\Classes\ClipperOffset\Properties\ArcTolerance.htm	; ArcTolerance
IDH_1026=Docs\Units\ClipperLib\Classes\ClipperOffset\Properties\MiterLimit.htm	; MiterLimit
IDH_1035=Docs\Units\ClipperLib\Classes\PolyNode\_Body.htm	; PolyNode
IDH_1028=Docs\Units\ClipperLib\Classes\PolyNode\Methods\GetNext.htm	; GetNext
IDH_1029=Docs\Units\ClipperLib\Classes\PolyNode\Properties\ChildCount.htm	; ChildCount
IDH_1030=Docs\Units\ClipperLib\Classes\PolyNode\Properties\Childs.htm	; Childs
IDH_1031=Docs\Units\ClipperLib\Classes\PolyNode\Properties\Contour.htm	; Contour
IDH_1032=Docs\Units\ClipperLib\Classes\PolyNode\Properties\IsHole.htm	; IsHole
IDH_1033=Docs\Units\ClipperLib\Classes\PolyNode\Properties\IsOpen.htm	; IsOpen
IDH_1034=Docs\Units\ClipperLib\Classes\PolyNode\Properties\Parent.htm	; Parent
IDH_1039=Docs\Units\ClipperLib\Classes\PolyTree\_Body.htm	; PolyTree
IDH_1036=Docs\Units\ClipperLib\Classes\PolyTree\Methods\Clear.htm	; Clear
IDH_1037=Docs\Units\ClipperLib\Classes\PolyTree\Methods\GetFirst.htm	; GetFirst
IDH_1038=Docs\Units\ClipperLib\Classes\PolyTree\Properties\Total.htm	; Total
IDH_1040=Docs\Units\ClipperLib\Functions\Area.htm	; Area
IDH_1041=Docs\Units\ClipperLib\Functions\CleanPolygon.htm	; CleanPolygon
IDH_1042=Docs\Units\ClipperLib\Functions\CleanPolygons.htm	; CleanPolygons
IDH_1043=Docs\Units\ClipperLib\Functions\ClosedPathsFromPolyTree.htm	; ClosedPathsFromPolyTree
IDH_1044=Docs\Units\ClipperLib\Functions\MinkowskiDiff.htm	; MinkowskiDiff
IDH_1045=Docs\Units\ClipperLib\Functions\MinkowskiSum.htm	; MinkowskiSum
IDH_1046=Docs\Units\ClipperLib\Functions\OffsetPaths.htm	; OffsetPaths
IDH_1047=Docs\Units\ClipperLib\Functions\OpenPathsFromPolyTree.htm	; OpenPathsFromPolyTree
IDH_1048=Docs\Units\ClipperLib\Functions\Orientation.htm	; Orientation
IDH_1049=Docs\Units\ClipperLib\Functions\PointInPolygon.htm	; PointInPolygon
IDH_1050=Docs\Units\ClipperLib\Functions\PolyTreeToPaths.htm	; PolyTreeToPaths
IDH_1051=Docs\Units\ClipperLib\Functions\ReversePath.htm	; ReversePath
IDH_1052=Docs\Units\ClipperLib\Functions\ReversePaths.htm	; ReversePaths
IDH_1053=Docs\Units\ClipperLib\Functions\SimplifyPolygon.htm	; SimplifyPolygon
IDH_1054=Docs\Units\ClipperLib\Functions\SimplifyPolygons.htm	; SimplifyPolygons
IDH_1055=Docs\Units\ClipperLib\Types\CInt.htm	; CInt
IDH_1056=Docs\Units\ClipperLib\Types\ClipType.htm	; ClipType
IDH_1057=Docs\Units\ClipperLib\Types\EndType.htm	; EndType
IDH_1058=Docs\Units\ClipperLib\Types\InitOptions.htm	; InitOptions
IDH_1059=Docs\Units\ClipperLib\Types\IntPoint.htm	; IntPoint
IDH_1060=Docs\Units\ClipperLib\Types\IntRect.htm	; IntRect
IDH_1061=Docs\Units\ClipperLib\Types\JoinType.htm	; JoinType
IDH_1062=Docs\Units\ClipperLib\Types\Path.htm	; Path
IDH_1063=Docs\Units\ClipperLib\Types\Paths.htm	; Paths
IDH_1064=Docs\Units\ClipperLib\Types\PolyFillType.htm	; PolyFillType
IDH_1065=Docs\Units\ClipperLib\Types\PolyType.htm	; PolyType
IDH_1066=Docs\Units\ClipperLib\Types\ZFillCallback.htm	; ZFillCallback
IDH_1070=Scripts\SyntaxHighlighter\index.html	; Hello SyntaxHighlighter
