;//Map header file for CHM project
;//Automatically generated by Easy CHM.
;//Website : http://www.zipghost.com
;//Email   : webmaster@zipghost.com
;//Date    : 2017/3/9 星期四 16:34:27

;//NOTE:
;//All strings after the ";" are commnets, they will be ignored by the CHM Compiler.

#define IDH_1069	1069	; Redirect index.htm
#define IDH_1068	1068	; Graphics32 Help Docs\_Body.htm
#define IDH_1000	1000	; Changes Docs\Overview\Changes.htm
#define IDH_1002	1002	; Deprecated Docs\Overview\Deprecated.htm
#define IDH_1003	1003	; Example Docs\Overview\Example.htm
#define IDH_1004	1004	; FAQ Docs\Overview\FAQ.htm
#define IDH_1005	1005	; License Docs\Overview\License.htm
#define IDH_1007	1007	; Overview Docs\Overview\_Body.htm
#define IDH_1006	1006	; Rounding Docs\Overview\Rounding.htm
#define IDH_1001	1001	; 变化 Docs\Overview\Changes_ZH.html
#define IDH_1067	1067	; ClipperLib Docs\Units\ClipperLib\_Body.htm
#define IDH_1014	1014	; Clipper Docs\Units\ClipperLib\Classes\Clipper\_Body.htm
#define IDH_1008	1008	; Constructor Docs\Units\ClipperLib\Classes\Clipper\Methods\Constructor.htm
#define IDH_1009	1009	; Execute Docs\Units\ClipperLib\Classes\Clipper\Methods\Execute.htm
#define IDH_1010	1010	; PreserveCollinear Docs\Units\ClipperLib\Classes\Clipper\Properties\PreserveCollinear.htm
#define IDH_1011	1011	; ReverseSolution Docs\Units\ClipperLib\Classes\Clipper\Properties\ReverseSolution.htm
#define IDH_1012	1012	; StrictlySimple Docs\Units\ClipperLib\Classes\Clipper\Properties\StrictlySimple.htm
#define IDH_1013	1013	; ZFillFunction Docs\Units\ClipperLib\Classes\Clipper\Properties\ZFillFunction.htm
#define IDH_1019	1019	; ClipperBase Docs\Units\ClipperLib\Classes\ClipperBase\_Body.htm
#define IDH_1015	1015	; AddPath Docs\Units\ClipperLib\Classes\ClipperBase\Methods\AddPath.htm
#define IDH_1016	1016	; AddPaths Docs\Units\ClipperLib\Classes\ClipperBase\Methods\AddPaths.htm
#define IDH_1017	1017	; Clear Docs\Units\ClipperLib\Classes\ClipperBase\Methods\Clear.htm
#define IDH_1018	1018	; GetBounds Docs\Units\ClipperLib\Classes\ClipperBase\Methods\GetBounds.htm
#define IDH_1027	1027	; ClipperOffset Docs\Units\ClipperLib\Classes\ClipperOffset\_Body.htm
#define IDH_1020	1020	; AddPath Docs\Units\ClipperLib\Classes\ClipperOffset\Methods\AddPath.htm
#define IDH_1021	1021	; AddPaths Docs\Units\ClipperLib\Classes\ClipperOffset\Methods\AddPaths.htm
#define IDH_1022	1022	; Clear Docs\Units\ClipperLib\Classes\ClipperOffset\Methods\Clear.htm
#define IDH_1023	1023	; Constructor Docs\Units\ClipperLib\Classes\ClipperOffset\Methods\Constructor.htm
#define IDH_1024	1024	; Execute Docs\Units\ClipperLib\Classes\ClipperOffset\Methods\Execute.htm
#define IDH_1025	1025	; ArcTolerance Docs\Units\ClipperLib\Classes\ClipperOffset\Properties\ArcTolerance.htm
#define IDH_1026	1026	; MiterLimit Docs\Units\ClipperLib\Classes\ClipperOffset\Properties\MiterLimit.htm
#define IDH_1035	1035	; PolyNode Docs\Units\ClipperLib\Classes\PolyNode\_Body.htm
#define IDH_1028	1028	; GetNext Docs\Units\ClipperLib\Classes\PolyNode\Methods\GetNext.htm
#define IDH_1029	1029	; ChildCount Docs\Units\ClipperLib\Classes\PolyNode\Properties\ChildCount.htm
#define IDH_1030	1030	; Childs Docs\Units\ClipperLib\Classes\PolyNode\Properties\Childs.htm
#define IDH_1031	1031	; Contour Docs\Units\ClipperLib\Classes\PolyNode\Properties\Contour.htm
#define IDH_1032	1032	; IsHole Docs\Units\ClipperLib\Classes\PolyNode\Properties\IsHole.htm
#define IDH_1033	1033	; IsOpen Docs\Units\ClipperLib\Classes\PolyNode\Properties\IsOpen.htm
#define IDH_1034	1034	; Parent Docs\Units\ClipperLib\Classes\PolyNode\Properties\Parent.htm
#define IDH_1039	1039	; PolyTree Docs\Units\ClipperLib\Classes\PolyTree\_Body.htm
#define IDH_1036	1036	; Clear Docs\Units\ClipperLib\Classes\PolyTree\Methods\Clear.htm
#define IDH_1037	1037	; GetFirst Docs\Units\ClipperLib\Classes\PolyTree\Methods\GetFirst.htm
#define IDH_1038	1038	; Total Docs\Units\ClipperLib\Classes\PolyTree\Properties\Total.htm
#define IDH_1040	1040	; Area Docs\Units\ClipperLib\Functions\Area.htm
#define IDH_1041	1041	; CleanPolygon Docs\Units\ClipperLib\Functions\CleanPolygon.htm
#define IDH_1042	1042	; CleanPolygons Docs\Units\ClipperLib\Functions\CleanPolygons.htm
#define IDH_1043	1043	; ClosedPathsFromPolyTree Docs\Units\ClipperLib\Functions\ClosedPathsFromPolyTree.htm
#define IDH_1044	1044	; MinkowskiDiff Docs\Units\ClipperLib\Functions\MinkowskiDiff.htm
#define IDH_1045	1045	; MinkowskiSum Docs\Units\ClipperLib\Functions\MinkowskiSum.htm
#define IDH_1046	1046	; OffsetPaths Docs\Units\ClipperLib\Functions\OffsetPaths.htm
#define IDH_1047	1047	; OpenPathsFromPolyTree Docs\Units\ClipperLib\Functions\OpenPathsFromPolyTree.htm
#define IDH_1048	1048	; Orientation Docs\Units\ClipperLib\Functions\Orientation.htm
#define IDH_1049	1049	; PointInPolygon Docs\Units\ClipperLib\Functions\PointInPolygon.htm
#define IDH_1050	1050	; PolyTreeToPaths Docs\Units\ClipperLib\Functions\PolyTreeToPaths.htm
#define IDH_1051	1051	; ReversePath Docs\Units\ClipperLib\Functions\ReversePath.htm
#define IDH_1052	1052	; ReversePaths Docs\Units\ClipperLib\Functions\ReversePaths.htm
#define IDH_1053	1053	; SimplifyPolygon Docs\Units\ClipperLib\Functions\SimplifyPolygon.htm
#define IDH_1054	1054	; SimplifyPolygons Docs\Units\ClipperLib\Functions\SimplifyPolygons.htm
#define IDH_1055	1055	; CInt Docs\Units\ClipperLib\Types\CInt.htm
#define IDH_1056	1056	; ClipType Docs\Units\ClipperLib\Types\ClipType.htm
#define IDH_1057	1057	; EndType Docs\Units\ClipperLib\Types\EndType.htm
#define IDH_1058	1058	; InitOptions Docs\Units\ClipperLib\Types\InitOptions.htm
#define IDH_1059	1059	; IntPoint Docs\Units\ClipperLib\Types\IntPoint.htm
#define IDH_1060	1060	; IntRect Docs\Units\ClipperLib\Types\IntRect.htm
#define IDH_1061	1061	; JoinType Docs\Units\ClipperLib\Types\JoinType.htm
#define IDH_1062	1062	; Path Docs\Units\ClipperLib\Types\Path.htm
#define IDH_1063	1063	; Paths Docs\Units\ClipperLib\Types\Paths.htm
#define IDH_1064	1064	; PolyFillType Docs\Units\ClipperLib\Types\PolyFillType.htm
#define IDH_1065	1065	; PolyType Docs\Units\ClipperLib\Types\PolyType.htm
#define IDH_1066	1066	; ZFillCallback Docs\Units\ClipperLib\Types\ZFillCallback.htm
#define IDH_1070	1070	; Hello SyntaxHighlighter Scripts\SyntaxHighlighter\index.html
